auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.26.1": "glongzh/kube-controllers:v3.26.1"
