auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "quay.io/jetstack/cert-manager-webhook:v1.6.3": "glongzh/cert-manager-webhook:v1.6.3"
  "quay.io/jetstack/cert-manager-cainjector:v1.6.3": "glongzh/cert-manager-cainjector:v1.6.3"
  "quay.io/jetstack/cert-manager-controller:v1.6.3": "glongzh/cert-manager-controller:v1.6.3"
