auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # kubernetes
  "registry.cn-qingdao.aliyuncs.com/sealer-io/kubernetes:v1.19.8": "glongzh/sealer-kubernetes:v1.19.8"
