auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "registry.cn-beijing.aliyuncs.com/kubesphereio/cni:v3.26.1": "glongzh/cni:v3.26.1"
  "registry.cn-beijing.aliyuncs.com/kubesphereio/pod2daemon-flexvol:v3.26.1": "glongzh/pod2daemon-flexvol:v3.26.1"
  "registry.cn-beijing.aliyuncs.com/kubesphereio/node:v3.26.1": "glongzh/node:v3.26.1"
  "registry.cn-beijing.aliyuncs.com/kubesphereio/typha:v3.26.1": "glongzh/typha:v3.26.1"
