auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond:v5.15.2-dind-allinone": "glongzh/rainbond:v5.15.2-dind-allinone"
