auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "ghcr.io/resmoio/kubernetes-event-exporter:latest": "glongzh/kubernetes-event-exporter:latest"
