auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "registry.cn-beijing.aliyuncs.com/kubesphereio/nginx-ingress-controller:v1.3.1": "glongzh/nginx-ingress-controller:v1.3.1"
